name: VariousClutter
main: com.balugaq.variousclutter.VariousClutter
depend: [ Slimefun ]
authors: [ balugaq ]
website: https://github.com/balugaq/VariousClutter
version: ${project.version}
api-version: 1.20
